# Generated by Django 4.2.19 on 2025-04-07 16:17

import cloudinary.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gadget_id', models.IntegerField(unique=True)),
                ('gadget_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('featured_image', cloudinary.models.CloudinaryField(default='default', max_length=255, verbose_name='image')),
                ('detail_description', models.TextField()),
                ('intended_use', models.CharField(max_length=300)),
                ('warning', models.CharField(default='No warning', max_length=2000)),
                ('minimum_usage_age', models.IntegerField(default='18')),
                ('unit_rent_price', models.IntegerField(default=0)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('short_description', models.CharField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gadgets', to='shop.category')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gadget_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['gadget_name'],
            },
        ),
        migrations.CreateModel(
            name='Renting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default='')),
                ('price', models.IntegerField(default=0)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('start_date', models.DateField(default=datetime.date.today, validators=[shop.models.Renting.Date_validation])),
                ('end_date', models.DateField(default=datetime.date.today, validators=[shop.models.Renting.Date_validation])),
                ('number_days_rent', models.PositiveIntegerField(default='')),
                ('address', models.CharField(default='', max_length=300)),
                ('email', models.EmailField(default='', max_length=250)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.IntegerField(choices=[(0, 'peding'), (1, 'complete')], default=0)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter', to=settings.AUTH_USER_MODEL)),
                ('gadget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renting_item', to='shop.gadget')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default='18')),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250)),
                ('shipping_address', models.CharField(default='', max_length=2000)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
