# Generated by Django 4.2.19 on 2025-03-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(default='18'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_address',
            field=models.TextField(default=''),
        ),
    ]
