# Generated by Django 4.2.19 on 2025-03-27 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_rename_name_category_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gadget_id', models.IntegerField(default=0)),
                ('gadget_name', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('category_short_desc', models.TextField()),
                ('category_detail_desc', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gadgets', to='shop.category')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gadget_create', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['gadget_name'],
            },
        ),
    ]
