# Generated by Django 4.2.19 on 2025-03-27 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_gadget'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadget',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gadgets', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='category_detail_desc',
            field=models.TextField(),
        ),
    ]
