# Generated by Django 4.2.19 on 2025-03-30 18:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_gadget_updated_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('address', models.CharField(default='', max_length=300)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.IntegerField(choices=[(0, 'Unpaid'), (1, 'Paid')], default=0)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gadget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.gadget')),
            ],
        ),
    ]
