# Generated by Django 4.2.19 on 2025-03-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_gadget_category_alter_gadget_category_detail_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadget',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
