# Generated by Django 4.2.19 on 2025-03-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_renting'),
    ]

    operations = [
        migrations.AddField(
            model_name='renting',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='renting',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
