# Generated by Django 4.2.19 on 2025-03-27 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_gadget_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gadget',
            old_name='category_detail_desc',
            new_name='gadget_detail_desc',
        ),
        migrations.RenameField(
            model_name='gadget',
            old_name='category_short_desc',
            new_name='gadget_short_desc',
        ),
    ]
