# Generated by Django 4.2.19 on 2025-03-30 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_renting_first_name_renting_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renting',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='renting',
            name='gadget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renting_item', to='shop.gadget'),
        ),
    ]
