# Generated by Django 4.2.19 on 2025-04-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_renting_end_date_alter_renting_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='renting',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
