# Generated by Django 4.2.19 on 2025-04-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_renting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='renting',
            name='email',
            field=models.EmailField(default='', max_length=250),
        ),
    ]
