# Generated by Django 4.2.19 on 2025-04-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_renting_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='renting',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
