# Generated by Django 4.2.19 on 2025-04-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_renting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='renting',
            name='number_days_rent',
            field=models.IntegerField(default=1),
        ),
    ]
