# Generated by Django 4.2.19 on 2025-04-04 21:10

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_renting_number_days_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renting',
            name='number_days_rent',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='renting',
            name='quantity',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='renting',
            name='start_date',
            field=models.DateField(default='', validators=[shop.models.Renting.Date_validation]),
        ),
    ]
