# Generated by Django 4.2.19 on 2025-04-05 02:17

import datetime
from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_renting_number_days_rent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renting',
            name='start_date',
            field=models.DateField(default=datetime.date.today, validators=[shop.models.Renting.Date_validation]),
        ),
    ]
